### ISSUE TITLE
Suggestion: Changing method of hashing passwords

### ISSUE THREAD

**Issue by Mester** [rmotr-group-projects/pyp-u6-c1-flask-twitter-clone#5]
`werkzeug` already has some methods that are very useful to use in hashing passwords, `check_password_hash` and `generate_password_hash`. 

This could be better since it's part of Flask already, it's more secure and robust than manually hashing, and it's simpler than having to fiddle around with md5 and encodings and such.

The docs are here: http://werkzeug.pocoo.org/docs/0.11/utils/#module-werkzeug.security 

And some examples here http://flask.pocoo.org/snippets/54/

Of course tests would need to be changed as well if this were to be implemented.

**Comment by santiagobasulto** [comment]
Thanks very much Adrian! We'll keep MD5 as it's the simplest example, but I've included a note in the README highlighting your comment and a link to this issue: https://github.com/rmotr-group-projects/pyp-u6-c1-flask-twitter-clone/commit/8d4cc5978ddf95554914b11ec1033689e6013e80

Everybody looking at it from the README, feel free to chime in.
